dependencies:
- name: mysql
  version: 10.3.0
  repository: https://charts.bitnami.com/bitnami
  condition: mysql.enabled
- name: redis
  version: 20.7.0
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: mailhog
  version: 5.0.2
  repository: https://codecentric.github.io/helm-charts
  condition: mailhog.enabled